# Dev overrides for worker
image:
  repository: "848928399250.dkr.ecr.ap-south-1.amazonaws.com/worker-service"
  tag: "ee78e36a73e5109d20120c73b6c94cb2681d5507"
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::848928399250:role/gitops-worker-dev
