# Staging overrides for worker
image:
  repository: "# TODO: set with ECR repo URL for worker"
  tag: ""
replicaCount: 1
keda:
  minReplicaCount: 1
  maxReplicaCount: 20
imageUpdater:
  enabled: true
serviceAccount:
  annotations:
    # TODO: annotate with eks.amazonaws.com/role-arn for IRSA
    {}
