# Dev overrides for worker
image:
  repository: "848928399250.dkr.ecr.ap-south-1.amazonaws.com/worker-service"
  tag: "30dc38fe8573c0f6d81d0e3f0803a53bb5b985f6"
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::848928399250:role/gitops-worker-dev
