# Prod overrides for worker
image:
  repository: "848928399250.dkr.ecr.ap-south-1.amazonaws.com/worker-service"
  tag: ""
replicaCount: 2
keda:
  minReplicaCount: 2
  maxReplicaCount: 50
imageUpdater:
  enabled: false
serviceAccount:
  annotations:
    # TODO: set production IRSA role ARN here
    {}
