# Staging overrides for worker
image:
  repository: "848928399250.dkr.ecr.ap-south-1.amazonaws.com/worker-service"
  tag: "latest"
replicaCount: 1
keda:
  minReplicaCount: 1
  maxReplicaCount: 20
imageUpdater:
  enabled: true
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::848928399250:role/gitops-worker-staging
