# Dev overrides - auto-deploy by CI
image:
  repository: "848928399250.dkr.ecr.ap-south-1.amazonaws.com/api-service"
  tag: "e6c1bb5743dc7c93bfe073b1281ec5f78b1a6ae5"
  pullPolicy: IfNotPresent
replicaCount: 1
hpa:
  enabled: false

ingress:
  enabled: false

serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::848928399250:role/gitops-api-dev
