# Dev overrides - auto-deploy by CI
image:
  repository: "848928399250.dkr.ecr.ap-south-1.amazonaws.com/api-service"
  tag: "07d909123a36273656b357299202c51618a212b7"
  pullPolicy: IfNotPresent
replicaCount: 1
hpa:
  enabled: false

serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::848928399250:role/gitops-api-dev
