# Prod overrides
image:
  repository: "848928399250.dkr.ecr.ap-south-1.amazonaws.com/api-service"
  tag: "b65b2a5a5abcaf595ad07142f17b39a665cd1e78" # Set to promoted immutable tag
replicaCount: 3
hpa:
  enabled: true
  minReplicas: 3
  maxReplicas: 12
imageUpdater:
  enabled: false
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::848928399250:role/gitops-api-prod
