# Staging overrides
image:
  repository: "848928399250.dkr.ecr.ap-south-1.amazonaws.com/api-service"
  tag: "" # CI will update with commit SHA on promotion
replicaCount: 2
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
imageUpdater:
  enabled: true
serviceAccount:
  annotations:
    # TODO: annotate with eks.amazonaws.com/role-arn for IRSA if using
    # eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/ExternalSecretsRole
    {}
