# Prod overrides
image:
  repository: "848928399250.dkr.ecr.ap-south-1.amazonaws.com/api-service"
  tag: "" # Set to promoted immutable tag
replicaCount: 3
hpa:
  enabled: true
  minReplicas: 3
  maxReplicas: 12
imageUpdater:
  enabled: false
serviceAccount:
  annotations:
    # TODO: set production IRSA role ARN here
    {}
