# Dev overrides - auto-deploy by CI
image:
  repository: "848928399250.dkr.ecr.ap-south-1.amazonaws.com/api-service"
  tag: "e3c5ac52ce39907698a43e3428a687e603f48478"
  pullPolicy: IfNotPresent
replicaCount: 1
hpa:
  enabled: false

serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::848928399250:role/gitops-api-dev
