# Staging overrides
image:
  repository: "848928399250.dkr.ecr.ap-south-1.amazonaws.com/api-service"
  tag: "latest" # replace with promoted immutable tag when ready
replicaCount: 2
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
imageUpdater:
  enabled: true
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::848928399250:role/gitops-api-staging
