apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (include "worker-service.fullname" .) .Values.serviceAccount.name | quote }}
  labels:
    app: {{ include "worker-service.name" . }}
  annotations:
{{ toYaml .Values.serviceAccount.annotations | indent 4 }}
